[package]
authors = ["Max Block <maxblock@pm.me>"]
edition = "2018"
name = "learn"
version = "0.1.0"

[dependencies]
rocket = "0.4.5"
rocket_contrib = {version = "0.4.5", default-features = false, features = ["json"]}
serde = {version = "1.0.116", features = ["derive"]}
